title: Awesome Mental Health Links in Canada
description: A curated list of mental health resources, services, and directories across Canada.
baseurl: ""
url: "https://axologic.github.io/awesome-mental-health-canada"
markdown: kramdown
theme: jekyll-theme-hacker
