title: Awesome Mental Health Links in Canada
description: A curated list of mental health resources, services, and directories across Canada.
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: ""
url: "https://axologic.github.io/awesome-mental-health-canada"
markdown: kramdown